# Generated by Django 4.2.7 on 2023-12-09 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(max_length=255, unique=True)),
                ('plant_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlantCareGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('seasonal', models.CharField(max_length=255)),
                ('guide', models.TextField()),
                ('admin_name', models.CharField(max_length=255)),
                ('plant_image', models.ImageField(blank=True, null=True, upload_to='plant_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('contact', models.CharField(max_length=15)),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('plant_care_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SanctuaryGarden.plantcareguide')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SanctuaryGarden.category')),
                ('plant_care_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SanctuaryGarden.plantcareguide')),
            ],
        ),
    ]
