# Generated by Django 4.2.6 on 2024-02-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SanctuaryGarden', '0002_alter_profile_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantcareguide',
            name='plant_image',
        ),
        migrations.AddField(
            model_name='plantcareguide',
            name='photo',
            field=models.ImageField(blank=True, default='default_photo.jpg', null=True, upload_to='plant_photos/'),
        ),
    ]
