# Generated by Django 4.2.6 on 2024-02-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SanctuaryGarden', '0003_remove_plantcareguide_plant_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantcareguide',
            name='status',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
